[package]
name = "twitar"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "playtweet"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.16", features = ["client", "http2", "runtime", "tcp"]}
url = "2.2.2"
pkce = "0.1.1"
config = "0.11.0"
dotenv = "0.15.0"